name: Post-Merge Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev
  workflow_dispatch:
  
env:
  TEST_1: ${{ vars.TEST_1 || 'test_1_default' }}
  TEST_2: ${{ github.ref_name }}_TEST_2
  #TARGET_ENV: ${{ github.ref_name == 'dev' && 'dev' || github.ref_name == 'main' && 'test' || '' }}
  TARGET_ENV: ${{github.ref_name == 'main' && 'test' || ''}}
  ENV_MAP: '{"key1": "value1"}'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # 定义组名
  cancel-in-progress: false # 如果已经有正在运行的，等待它结束，而不是取消它
jobs:
  run_on_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run post-merge tasks
        run: |
          echo "PR was merged into main! Running deployment..."
          echo "${{ github.workflow }}-${{ github.ref }}"
          echo "${TEST_1}"
          echo "${TEST_2}"
          echo "${TARGET_ENV}"
          if [ -z ${TARGET_ENV} ]; then
            echo "===============1"
          else
            echo "===============2"
          fi
          ls -l
          cat test2.txt
          echo "${{ vars.TEST_1 }} ${{ secrets.GITHUB_TOKEN }},  ${{ secrets.TEST_SECRET }}"
          sleep 60
  test:
    #if: github.event.pull_request.merged == true
    runs-on: test
    steps:
      - name: test
        run: |
          echo "=====================3"
          echo "${TARGET_ENV}"
          echo "${{ github.workflow }}-${{ github.ref }}"
          KEY="key1"
          echo $ENV_MAP
          echo ${ENV_MAP} | jq -r ".key1"
          result=$(echo ${ENV_MAP} | jq -r ".\"${KEY}\"")
          echo $result
          echo "==================1"
          #ENV_MAP='${{ vars.ENV_MAP || '{"key1":"value1"}' }}'
          if [ -n ${{ vars.ENV_MAP }} ]; then
            ENV_MAP='${{ vars.ENV_MAP }}'
          fi
          echo $ENV_MAP
          echo ${ENV_MAP} | jq -r ".key1"
          echo "==================2"
          result=$(echo "${ENV_MAP}" | jq -r ".\"${KEY}\"")
          echo $result
