name: test tag Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  run_on_merge:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run post-merge tasks
        run: |
          echo "github.ref====="${{github.ref}}
          echo "github.base_ref====="${{github.base_ref}}
          echo "github.ref====="${{github.ref}}
          ls -l 
